# Environment variables to be defined in the build configuration:
# AUTH0_TEST_CLIENT_ID = Client id to use in test
# AUTH0_TEST_DOMAIN = Domain to use in test
# AUTH0_TEST_AUDIENCE = API Audience to use in test

# Jobs and Workflows
version: 2.1
parameters:
  machine_image:
    type: string
    default: ubuntu-2004:202201-02
orbs:
  node: circleci/node@5.0
jobs:
  checkout:
    machine:
      image: << pipeline.parameters.machine_image >>
    steps:
      - checkout
      - run: git clone https://github.com/auth0-samples/spa-quickstarts-tests scripts
      - persist_to_workspace:
          root: ~/
          paths:
            - project
            - scripts
  sample-01:
    parameters:
      app-directory:
        type: string
        default: "Sample-01"
        description: "The root directory of the application to run"
    machine:
      image: << pipeline.parameters.machine_image >>
    environment:
      - AUTH0_CFG: <<parameters.app-directory>>/auth_config.json
      - AUTH0_EXAMPLE_CFG: <<parameters.app-directory>>/auth_config.json.example
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Replace Auth0 test credentials
          command: |
            sed \
              -e "s/{DOMAIN}/$AUTH0_TEST_DOMAIN/g" \
              -e "s/{CLIENT_ID}/$AUTH0_TEST_CLIENT_ID/g" \
              -e "s/{API_IDENTIFIER}/$AUTH0_TEST_API_IDENTIFIER/g" \
              $AUTH0_EXAMPLE_CFG > $AUTH0_CFG
      - node/install-packages:
          pkg-manager: npm
          app-dir: <<parameters.app-directory>>
      - run:
          name: Run unit tests
          working_directory: <<parameters.app-directory>>
          command: npm run test:ci
  login:
    parameters:
      app-directory:
        type: string
        default: "Sample-01"
        description: "The root directory of the application to run"
    machine:
      image: << pipeline.parameters.machine_image >>
    environment:
      - AUTH0_CFG: <<parameters.app-directory>>/auth_config.json
      - AUTH0_EXAMPLE_CFG: <<parameters.app-directory>>/auth_config.json.example
      - SAMPLE_PATH: <<parameters.app-directory>>
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Replace Auth0 test credentials
          command: |
            sed \
              -e "s/{DOMAIN}/$AUTH0_TEST_DOMAIN/g" \
              -e "s/{CLIENT_ID}/$AUTH0_TEST_CLIENT_ID/g" \
              -e "s/{API_IDENTIFIER}/$AUTH0_TEST_API_IDENTIFIER/g" \
              $AUTH0_EXAMPLE_CFG > $AUTH0_CFG
      - run:
          name: Build pull request
          command: |
            docker build -t $CIRCLE_JOB ./$SAMPLE_PATH
            docker run -d -p 4200:4200 --name $CIRCLE_SHA1 $CIRCLE_JOB
          background: true
      - run:
          name: Wait for app to be available
          command: |
            sleep 70
            docker run --network host --rm appropriate/curl --retry 8 --retry-connrefused -v localhost:4200
      - run:
          name: Run tests
          command: |
            docker create --env "SAMPLE_PORT=4200" --network host --name tester codeception/codeceptjs codeceptjs run-multiple --all --steps 
            docker cp $(pwd)/lock_login_test.js tester:/tests/lock_login_test.js
            docker cp $(pwd)/codecept.conf.js tester:/tests/codecept.conf.js
            docker start -i tester
          working_directory: scripts
      - run:
          name: Copy app container logs
          command: |
            mkdir -p /tmp/out
            docker logs $CIRCLE_SHA1 > /tmp/out/app_logs.log
            docker cp tester:/tests/out /tmp/
          when: on_fail
      - store_artifacts:
          path: /tmp/out
workflows:
  version: 2
  quickstarts_login:
    jobs:
      - checkout:
          context: Quickstart SPA Test
      - sample-01:
          app-directory: Sample-01
          requires:
            - checkout
      - sample-01:
          name: standalone
          app-directory: Standalone
          requires:
            - checkout
      - login:
          context: Quickstart SPA Test
          app-directory: Sample-01
          requires:
            - checkout
      - login:
          name: login-standalone
          context: Quickstart SPA Test
          app-directory: Standalone
          requires:
            - checkout
            - login